### PR TITLE
[AGORA-1906] Prettier linting in GHA

### PR DESCRIPTION
**Pull request by Flip-Liquid**
## PR-Codex overview
The focus of this PR is to update code across multiple files for consistency and correctness. 

### Detailed summary
- Fixed array type syntax in various files
- Adjusted CSS properties for better readability
- Updated function names and logic for clarity
- Corrected type definitions for better accuracy

> The following files were skipped due to too many changes: `src/lib/contracts/generated/OptimismToken.ts`, `src/lib/contracts/generated/GovernanceToken.ts`, `src/lib/contracts/generated/EtherfiToken.ts`, `src/lib/contracts/generated/common.ts`, `src/lib/contracts/generated/AlligatorOPV5.ts`, `src/lib/contracts/generated/OptimismGovernor.ts`, `src/lib/contracts/generated/NounsGovernor.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yitongzhang** [comment]
me like

**Comment by ferrodri** [comment]
Nice! 🚢

**Review by andreitr — APPROVED** [review]
The most boring PR review... SHIP IT 🚢 🚢 🚢

**Review by ferrodri — APPROVED** [review]
Nice! 🚢

**Pull request merged**
