### PR TITLE
wojeth/agora-1315 Needs my vote

### PR DESCRIPTION
**Pull request by wojtekwtf**
video: https://www.loom.com/share/0b2bc957ac3e40619cc0ef6adca00e82

note: it takes a moment to load. @yitongzhang lmk if i should place a skeleton there

### CODE REVIEW

**Comment by yitongzhang** [comment]
Hmm preview doesn't work. does it also take a long time to load if you're already signed in? A couple of questions for a potential skeleton state: 

1. We won't know how many proposals there will be in the skeleton right?
2. Is there a way to know if there will be any proposals in need my votes? would not be such a good experience to show a skeleton

Anyway – if the answer is that we can't get either, then we don't do the skeleton cause it won't be a better experience

**Comment by wojtekwtf** [comment]
> Hmm preview doesn't work. does it also take a long time to load if you're already signed in?
Took around 10 seconds for me, hard to tell if it's just on dev or in prod too

> We won't know how many proposals there will be in the skeleton right?
Nope

> Is there a way to know if there will be any proposals in need my votes? would not be such a good experience to show a skeleton
Also nope

Both questions would require additional db queries

pinging @stepandel to help with the optimization

**Comment by wojtekwtf** [comment]
@yitongzhang i optimized the query, the speed on average is quite good, takes around 1 second to display "Needs my vote" after loading "All proposals"

I experience the delay when i open the preview link for the first time — I don't really know why. But general performance should be fine now, please lmk what do you think.

**Comment by yitongzhang** [comment]
This is sick! tysm

**Review by yitongzhang — APPROVED** [review]

**Pull request merged**
