### PR TITLE
AGORA-1501 when clicking the info icon for your total delegatable votes

### PR DESCRIPTION
**Pull request by Dom-Mac**
# Scrollable list - Many delegations
Screenshot 2024-01-29 at 18 13 51

# No delegations
Screenshot 2024-01-29 at 18 17 25

---

### Focus of this PR:
This PR focuses on adding a new function `fetchAllForAdvancedDelegation` and making changes to the `AdvancedDelegateDialog` component.

### Detailed summary:
- Added `fetchAllForAdvancedDelegation` function to fetch all data needed for advanced delegation.
- Updated `AdvancedDelegateDialog` component to use the new function and display additional information.
- Added an info dialog to show detailed information about available balance, total balance, delegators, and direct delegated voting power.

> The following files were skipped due to too many changes: `src/components/Dialogs/AdvancedDelegateDialog/AdvancedDelegateDialog.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by kent** [comment]
@yitongzhang looking at this one, do you want the scroll list to break out of the modal like that? I was expecting it to stay contained within the modal.

**Comment by yitongzhang** [comment]
@kent all good – no harm in it breaking out a bit imo. gives us a few more rows to diplay info. 

@Dom-Mac:
1. can you make sure that we do have a max height on the element so that it doesn't go off the page?
2. can you also add a shadow (new-default) on the scrollable list when it's expanded to show that it's "above" the modal? I think that'll also help with Kent's point

**Comment by Dom-Mac** [comment]
1 - Iirc max-height is in place, will check. Anyway this impact more those with a long (i guess potentially infinite) list of delegators. A better ux in this case could be:
- sorting for vp 
- load only first n
- display a  '+200 others' button
- on click loads others -> scrolling with pagination 

Idk how many users we have now in this situation, so @yitongzhang @kent yours to schedule

2. Kk

**Comment by ferrodri** [comment]
Hi @kent @yitongzhang just added the shadow (new-default) on the scrollable list when it's expanded to show that it's "above" the modal. I can also confirm there is a max height in place so the element does not go off the page.

Here are some screenshots, please lmk if I can merge it
Screenshot 2024-02-12 at 15 44 11
Screenshot 2024-02-12 at 15 44 04
Screenshot 2024-02-12 at 15 42 45

**Comment by yitongzhang** [comment]
Perfect thank you! lgtm

**Review by yitongzhang — APPROVED** [review]

**Pull request merged**
