### PR TITLE
useSwitch network functionality done

### PR DESCRIPTION
**Pull request by ferrodri**
Preview link: https://agora-next-nogn2ql7x-voteagora.vercel.app/

This PR shows the button "Wrong Network" when user is not on OP chain:
Screenshot 2024-02-20 at 01 25 53
Screenshot 2024-02-20 at 01 26 03

---

## PR-Codex overview
The focus of this PR is to implement a switch network dialog feature for connecting to Optimism chain.

### Detailed summary
- Added `SwitchNetworkDialog` component for switching networks
- Updated `DialogProvider` to handle `SWITCH_NETWORK` type
- Implemented logic in `ConnectButton` to prompt network switch
- Defined `SwithcNetworkDialogType` in `dialogs.tsx`
- Utilized `useSwitchNetwork` and `useNetwork` hooks

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yitongzhang** [comment]
hi! quick question: did we check that connectkit doesn't have a built-in way to handle this? If i'm on polygon today, and try to connect to agora it shows this modal:

CleanShot 2024-02-20 at 09 05 53@2x


Is the idea that instead of letting users choose between Ethereum and Optimism, we want to force them to pick Optimism?

**Comment by yitongzhang** [comment]
If so, i think instead of show a red button and waiting for users to click, we can simply directly show a blocking modal like connectkit and skip to this step. Also let's add a small image here to make it look less like an error

image

**Comment by ferrodri** [comment]
Hi @yitongzhang here is the updated PR with the new UI and an updated logic so connectkit modal does not appear when in mainnet https://agora-next-gtzezs9qk-voteagora.vercel.app/

**Comment by yitongzhang** [comment]
Hi @ferrodri i don't see the new UI? can you record a video showing it?

**Comment by ferrodri** [comment]
> Hi @ferrodri i don't see the new UI? can you record a video showing it? I still see this: CleanShot 2024-02-26 at 08 16 17@2x

Here is the video: https://www.loom.com/share/d31dc443464947fa9e4824c5d83265b7?sid=25e1b882-a049-4567-b481-d5495faa2d59 thank you so much!

**Review by yitongzhang — APPROVED** [review]

**Comment by yitongzhang** [comment]
Are you sure there's no way to disable the conneckit modal for non-ethereum network? this seems unlikely. if there's truly no way, then i approved this PR to ship as is

**Comment by ferrodri** [comment]
> Are you sure there's no way to disable the conneckit modal for non-ethereum network? this seems unlikely. if there's truly no way, then i approved this PR to ship as is

I found a way, thank you for pushing me @yitongzhang, I will merge now!

**Pull request merged**
