### PR TITLE
Frodriguezhervias/agora 1435 build results page for rpgf

### PR DESCRIPTION
**Pull request by ferrodri**
Here is the preview link: https://agora-next-22ky7uagd-voteagora.vercel.app/
Here is the issue: https://linear.app/agora-app/issue/AGORA-1435/build-results-page-for-rpgf

### CODE REVIEW

**Comment by kent** [comment]
@ferrodri looking good. Can you clean up the loading glasses and center it like it is on the Proposals page right now it's over on the left. 
CleanShot 2024-01-25 at 08 00 56@2x

**Review by kent — COMMENTED** [review]
See my comment re: loading screen

**Comment by ferrodri** [comment]
Just fixed it @kent, thank you so much!

**Comment by ferrodri** [comment]
Just fixed it @kent, here is the new preview link: https://agora-next-9xyn536is-voteagora.vercel.app/

Quick question, should the glasses be removed from the whole project?

Thank you so much!

**Review by kent — COMMENTED** [review]
Sorry Fernando but there are some font issues in the Results table. See attached.

Font-size of the project name on the old site is much smaller and is not breaking onto multiple
CleanShot 2024-01-25 at 18 22 56@2x
 lines.

**Comment by ferrodri** [comment]
Hi @kent , thanks for the feedback. I did set this font size following the figma as we discussed (from what I remember) https://www.figma.com/file/PZYknWe4Y8kyszOXajhygG/Agora-designs?type=design&node-id=7210-69389&mode=design&t=GCVDEEgyWWyI8MaB-0

Changing it to 14px instead of 16px!

**Review by kent — APPROVED** [review]
Thank you

**Pull request merged**
