### PR TITLE
Ferrodri/agora 1551 various responsive issues

### PR DESCRIPTION
**Pull request by ferrodri**
Preview link: https://agora-next-m69tadsug-voteagora.vercel.app/

---

## PR-Codex overview
This PR focuses on updating the Tailwind CSS configuration and making UI improvements in various components. 

### Detailed summary:
- Updated `tailwind.config.js` to modify the spacing and minimum width values.
- Added `minWidth` breakpoint for desktop in `tailwind.config.js`.
- Updated the class names and styles in `Header.jsx`, `DelegateStatementContainer.tsx`, `PageContainer.tsx`, `BetaBanner.tsx`, `LogoLink.jsx`, and `page.tsx`.
- Improved the layout and responsiveness of the components in `Header.jsx`, `DelegateStatementContainer.tsx`, `PageContainer.tsx`, `BetaBanner.tsx`, `LogoLink.jsx`, and `page.tsx`.
- Added a new paragraph element with a class name in `DelegateStatementContainer.tsx`.
- Updated the class names and styles in `page.tsx` for better alignment and spacing.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yitongzhang** [comment]
This is looking good on the visual side ty! Minor issue – on mobile the logo on the left doesnt really work. Not part of this issue, but since you're here, could be addressed in the same PR too. There's no good solution here, but I would hide the Agora logo and the vertical bar on mobile and simply show only the OP logo

CleanShot 2024-02-07 at 15 49 59@2x

**Review by yitongzhang — APPROVED** [review]
Feel free to merge after addressing the issue above

**Comment by ferrodri** [comment]
@yitongzhang just resolved your comments, here is the preview link: https://agora-next-alfch19l8-voteagora.vercel.app/

Could you please merge since I am not authorized to merge into main

**Comment by stepandel** [comment]
my bad @ferrodri
updated permissions, you should be able to merge

**Pull request merged**
